#cloud-config
users:
  - default
  - name: circleci
    ssh-authorized-keys:
      - ${modelserver:sshPublicKey}
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash

runcmd:
  - bash /root/setup.sh
